events {}

http {
    server {
        listen 80;

        client_max_body_size 20M;

        location / {
            proxy_pass http://minio:9000;

            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;

            proxy_buffering off;
        }
    }
}